### PR TITLE
Added image repo and updated links

### PR DESCRIPTION
**Pull request by mpritter76**

### CODE REVIEW

**Comment by medyagh** [comment]
can you find the licence for the images?

**Review by medyagh — CHANGES_REQUESTED** [review]
Need clarification on the image licence

**Comment by mpritter76** [comment]
Free icons found here: https://www.iconfinder.com/search/?q=yellow+shield+shape&style=3d&price=free.

I've added an Author field as part of the image metadata referencing authors website. http://www.icons-land.com/

Metadata can be viewed using exiftool.

**Comment by medyagh** [comment]
Can't include that, need to find graphics with GPL or Apache2.

**Comment by milsonian** [comment]
These are Apache2:
https://github.com/google/material-design-icons (https://material.io/icons/)

Btw, did some looking and creative commons is not compatible w/ Apache2 but certain types of CC are with GPLv3..it gets a little complicated.

**Comment by milsonian** [comment]
P.S. I'm also not sure we could use GPL images, since our main license is Apache2 - it's not compatible in that direction (https://www.apache.org/licenses/GPL-compatibility.html).

**Pull request closed without merging**
